### ISSUE TITLE
Autograder trigger

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet#259] opened 2018-09-04 07:08 UTC
The autograder should be triggered when the student submits (or betcha).

This will allow the grader to grade as early as possible.

**Comment by indocomsoft** [comment] 2018-09-04 17:05
Isn't this already implemented? Refer to https://github.com/source-academy/cadet/blob/master/lib/cadet/assessments/assessments.ex#L350

**Comment by indocomsoft** [comment] 2018-09-04 17:06
@rrtheonlyone can help confirm. If it is already implemented then we can close this issue.

**Comment by indocomsoft** [comment] 2018-09-05 02:35
@tuesmiddt confirmed that this has been implemented. Will close this issue for now.

You can reopen this issue in case this feature is not working as expected.

**Closed by indocomsoft** 2018-09-05 02:35 UTC

**Comment by blackening** [comment] 2018-09-05 02:45
One of two things are broken. Either the autograder for all curve missions is broken, or the autograder is not triggered on submission.

![image](https://user-images.githubusercontent.com/1753927/45068126-9f8d0f80-b0f8-11e8-9f55-fab4ab6e0ba3.png)

**Comment by indocomsoft** [comment] 2018-09-05 02:47
According to the server log, it is running.

![image](https://user-images.githubusercontent.com/11135744/45068208-f09d0380-b0f8-11e8-89e0-4b907558fc72.png)

**Comment by tuesmiddt** [comment] 2018-09-05 02:51
https://github.com/source-academy/grader/pull/24

looks like curves grader is not in grader master yet

**Comment by blackening** [comment] 2018-09-05 03:04
Got it, the autograder cases are broken. Need to re-run them.
